### PR TITLE
Update cardmarket api urls to new ones

### PR DESCRIPTION
**Pull request by Creatan**
Cardmarket has updated their domain and old domain names won't work anymore. Updated URLs to reflect this change

### CODE REVIEW

**Review by nique21 — APPROVED** [review]
I was about to make the same changes. Thank you.

**Comment by tobob** [comment]
can someone merge it and make npm package release? @jsmrcaga ?

**Comment by tobob** [comment]
old endpoints have some struggles

**Review by jsmrcaga — APPROVED** [review]

**Comment by tobob** [comment]
thanks a lot!

**Comment by jsmrcaga** [comment]
@tobob of course! I also released a new version, sorry if i did not say, I am on holiday and havent touched my computer in a while :P

**Pull request merged**
